// <auto-generated />
namespace Vidly_Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PhoneNumberAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhoneNumberAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201912031007476_PhoneNumberAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
